version: '3.7'

services:

  # Frontend
  nginx:
    container_name: nginx
    build: ./backend/webserver
    restart: on-failure:3
    env_file: .env #IP whitelist
    environment:
      - domain=trans.ella-peeters.me
    networks:
      - frontend #Connects to database
      - backend #Connects to backend
    ports:
      - "80:80" #Http (-> https)
      - "443:443" #Https
    volumes:
      - /etc/ssl/trans_ella-peeters_me:/etc/ssl/trans_ella-peeters_me:ro #Mount SSL certificate
      - /home/lpeeters/.ssh/ella-peeters.me.key:/etc/ssh/ella-peeters.me.key:ro #Mount SSH key
      - ./backend/webserver/nginx.conf:/etc/nginx/nginx.conf:ro #Mount Nginx configuration
      - ./backend/webserver/ip_whitelist.js:/etc/nginx/ip_whitelist.js:ro #Mount IP whitelist fetching
      - ./frontend/test_environment:/var/www/html/test_environment:ro #Served statically for testing
      - ./frontend/production:/var/www/html/production:ro #Placeholder production

  # Backend database
  database:
    container_name: database
    build:
      context: .
      dockerfile: backend/database/Dockerfile
    restart: on-failure:3
    env_file: .env.backend
    environment:
      - domain=trans.ella-peeters.me
    depends_on:
      - nginx
    networks:
      - frontend #Connects to Nginx
      - database #Connects to authenticator
    volumes:
      - db-volume:/var/www/db
      - ./backend/database/api.js:/var/www/js/api.js:ro

  # Backend websocket
  websocket:
    container_name: websocket
    build:
      context: .
      dockerfile: backend/websocket/Dockerfile
    restart: on-failure:3
    env_file: .env.backend
    environment:
      - domain=trans.ella-peeters.me
    depends_on:
      - nginx
    networks:
      - frontend #Connects to Nginx
      - database #Connects to database
    volumes:
      - ./backend/websocket/ws.js:/var/www/ws/ws.js:ro

  # Backend authenticator
  authenticator:
    container_name: authenticator
    build: ./backend/authenticator
    restart: on-failure:3
    env_file: .google_credentials.env
    environment:
      - domain=trans.ella-peeters.me
    depends_on:
      - database
    networks:
      - database #Connects to database
      - backend #Connects to Nginx
    volumes:
      - ./backend/authenticator/google_authenticator.js:/srv/google_authenticator.js:ro
      - ./backend/authenticator/package.json:/srv/package.json:ro

  # Backend email server
  mailserver:
    container_name: mailserver
    build: ./backend/mailserver
    restart: on-failure:3
    env_file: .smtp_credentials.env
    environment:
      - domain=ella-peeters.me
    depends_on:
      - database
    #networks:
      #- database #Connects to database
      #- backend #Connects to Nginx
    ports:
      - "2525:2525" #Mailgun
    volumes:
      - /home/lpeeters/.ssh/ella-peeters.me_dkim_public.key:/etc/ssh/ella-peeters.me_dkim_public.key:ro #Mount public DKIM key
      - /home/lpeeters/.ssh/ella-peeters.me_dkim_private.key:/etc/ssh/ella-peeters.me_dkim_private.key:ro #Mount private DKIM key
      - ./backend/mailserver/client.js:/srv/client.js:ro
      - ./backend/mailserver/package.json:/srv/package.json:ro

volumes:
  db-volume:
    name: sqlite
    driver_opts:
      o: bind
      type: none
      device: ./data/sqlite

# Networks for frontend and backend
networks:
  frontend:
  backend:
  database:
