version: '3.7'

services:

  # Frontend
  nginx:
    container_name: nginx
    build: ./backend/webserver
    restart: on-failure:3
    env_file: .env #IP whitelist
    environment:
      - domain=trans.ella-peeters.me
    networks:
      - nginx-database
      - authenticator-nginx
      - mailserver-nginx
      - ws-nginx
    ports:
      - "80:80" #Http (-> https)
      - "443:443" #Https
    volumes:
      - /etc/ssl/trans_ella-peeters_me:/etc/ssl/trans_ella-peeters_me:ro #Mount SSL certificate
      - /home/lpeeters/.ssh/ella-peeters.me.key:/etc/ssh/ella-peeters.me.key:ro #Mount SSH key
      - ./backend/webserver/nginx.conf:/etc/nginx/nginx.conf:ro #Mount Nginx configuration
      - ./backend/webserver/ip_whitelist.js:/etc/nginx/ip_whitelist.js:ro #Mount IP whitelist fetching
      - ./frontend/test_environment:/var/www/html/test_environment:ro #Served statically for testing
      - ./frontend/production:/var/www/html/production:ro #Placeholder production

  # Backend database
  database:
    container_name: database
    build:
      context: .
      dockerfile: backend/database/Dockerfile
    restart: on-failure:3
    env_file: .env.backend
    environment:
      - domain=trans.ella-peeters.me
    depends_on:
      - nginx
    networks:
      - nginx-database
      - mailserver-database
      - authenticator-database
      - ws-database
    volumes:
      - db-volume:/var/www/db
      - ./backend/database/api.js:/var/www/js/api.js:ro

  # Backend websocket
  websocket:
    container_name: websocket
    build:
      context: .
      dockerfile: backend/websocket/Dockerfile
    restart: on-failure:3
    env_file: .env.backend
    environment:
      - domain=trans.ella-peeters.me
    depends_on:
      - nginx
    networks:
      - ws-nginx #Connects to Nginx
      - ws-database #Connects to database
    volumes:
      - ./backend/websocket/ws.js:/var/www/ws/ws.js:ro

  # Backend authenticator
  authenticator:
    container_name: authenticator
    build: ./backend/authenticator
    restart: on-failure:3
    env_file: .google_credentials.env
    environment:
      - domain=trans.ella-peeters.me
    depends_on:
      - database
    networks:
      - authenticator-nginx
      - authenticator-database
    volumes:
      - ./backend/authenticator/google_authenticator.js:/srv/google_authenticator.js:ro
      - ./backend/authenticator/package.json:/srv/package.json:ro

  # Backend email server
  mailserver:
    container_name: mailserver
    build: ./backend/mailserver
    restart: on-failure:3
    env_file: .smtp_credentials.env
    environment:
      - domain=ella-peeters.me
      - subDomain=trans.ella-peeters.me
    depends_on:
      - database
    networks:
      - mailserver-nginx
      - mailserver-database
    ports:
      - "2525:2525" #Mailgun
    volumes:
      - /home/lpeeters/.ssh/ella-peeters.me_dkim_public.key:/etc/ssh/ella-peeters.me_dkim_public.key:ro #Mount public DKIM key
      - /home/lpeeters/.ssh/ella-peeters.me_dkim_private.key:/etc/ssh/ella-peeters.me_dkim_private.key:ro #Mount private DKIM key
      - ./backend/mailserver/server.js:/srv/server.js:ro
      - ./backend/mailserver/mail.js:/srv/mail.js:ro
      - ./backend/mailserver/mail.html:/srv/mail.html:ro
      - ./backend/mailserver/package.json:/srv/package.json:ro

volumes:
  db-volume:
    name: sqlite
    driver_opts:
      o: bind
      type: none
      device: /srv/transcendence/data

# Networks for frontend and backend
networks:
  nginx-database:
  authenticator-nginx:
  authenticator-database:
  mailserver-nginx:
  mailserver-database:
  ws-database:
  ws-nginx:
