#Nginx JavaScript module library
load_module modules/ngx_http_js_module.so;

# Automatically determine number of workers based on available CPU cores
worker_processes auto;

# Maximum connections per worker
events
{
	worker_connections 1024;
}

# Make Nginx JavaScript scripting release environment variables exist
env SCHOOL_ETHERNET;
env SCHOOL_WIFI;
env ELLA;
env PCLAUS;

http
{
	# MIME types for correct content serving
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	# Http
	server
	{
		listen 80;
		listen [::]:80;

		# Resolve both root and www subdomain
		server_name ${domain} www.${domain};

		# Redirect http traffic to https
		location /
		{
			return 301 https://$host$request_uri;
		}
	}

	# Https
	server
	{
		listen 443 ssl;
		listen [::]:443 ssl;

		# Resolve both root and www subdomain
		server_name ${domain} www.${domain};

		# Use faster http protocol and hide Nginx version
		http2 on;
		server_tokens off;

		# SSL certificates
		ssl_certificate /etc/ssl/trans_ella-peeters_me/trans_ella-peeters_me.crt;
		ssl_certificate_key /etc/ssh/ella-peeters.me.key;
		ssl_trusted_certificate /etc/ssl/trans_ella-peeters_me/trans_ella-peeters_me.ca-bundle;

		# Enforce strong cipher suite and secure TLS protocols, preferring newer version
		ssl_ciphers HIGH:!aNULL:!MD5;
		ssl_protocols TLSv1.3 TLSv1.2;

		# Frontend's production
		location /
		{
			root /var/www/html/production;

			index index.html;
		}

		# Proxy pass to NodeJS API server
		location /api
		{
			proxy_pass http://server:3443;
			proxy_set_header Host $host;
			proxy_set_header X-Real-Ip $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		# Load in the JavaScript whitelist parser
		js_import whitelist from /etc/nginx/ip_whitelist.js;

		# Whitelist checking for the safe testing environment
		location /safe
		{
			js_content whitelist.check_ip;
		}

		# Serve the test environment internally
		location /test_environment
		{
			internal;

			root /var/www/html;
			index index.html;
		}

		# Serve static files with caching internally for the test environment
		location ~* ^/test_environment/(.+\.(css|js|png|jpg|jpeg|gif|ico|woff|woff2|ttf|eot|otf|svg))$
		{
			internal;

			root /var/www/html;
			expires max;
			access_log off;
		}

		# Deny access to hidden files
		location ~ /\.
		{
			deny all;
		}
	}

	# Log requests and errors
	access_log /dev/stdout;
	error_log /dev/stderr;
}
